[tox]
envlist =
    app,app-postgres,api,api-postgres

[testenv]
basepython = python3.12


[testenv:app]
deps = -r requirements.txt
setenv =
    CELERY_ALWAYS_EAGER=True
commands = pytest app/src/triplea {posargs:-n auto}

[testenv:app-postgres]
deps = -r requirements.txt
setenv =
    DATABASE_URL=postgresql://test:test@localhost:5432/triplea_test
    CELERY_ALWAYS_EAGER=True
commands = pytest app/src/triplea {posargs:-n auto}

[testenv:api]
deps = -r requirements.txt
setenv =
    CELERY_ALWAYS_EAGER=True
commands = pytest app/src/triplea_api {posargs:-n auto}

[testenv:api-postgres]
deps = -r requirements.txt
setenv =
    DATABASE_URL=postgresql://test:test@localhost:5432/triplea_test
    CELERY_ALWAYS_EAGER=True
commands = pytest app/src/triplea_api {posargs:-n auto}
