[tox]
envlist =
    app,app-postgres,api,api-postgres

[testenv]
basepython = python3.12


[testenv:app]
deps = -r requirements.txt
setenv =
    CELERY_ALWAYS_EAGER=True
    CELERY_TASK_ALWAYS_EAGER=True
commands = python manage.py test triplea{posargs} --parallel=1

[testenv:app-postgres]
deps = -r requirements.txt
setenv =
    DATABASE_URL=postgresql://test:test@localhost:5432/triplea_test
    CELERY_ALWAYS_EAGER=True
commands = python manage.py test triplea{posargs} --parallel=1

[testenv:api]
deps =
    webtest
    -r requirements.txt
setenv =
    CELERY_ALWAYS_EAGER=True
    CELERY_TASK_ALWAYS_EAGER=True
commands = python manage.py test triplea_api{posargs} --parallel=1

[testenv:api-postgres]
deps =
    webtest
    -r requirements.txt
setenv =
    DATABASE_URL=postgresql://test:test@localhost:5432/triplea_test
    CELERY_ALWAYS_EAGER=True
commands = python manage.py test triplea_api{posargs} --parallel=1
