# Generated by Django 4.0.1 on 2022-03-18 21:35

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models, connection
import django.db.models.deletion
import django.utils.timezone
import uuid

# UUID fields are great as primary keys but very slow when using large offset queries. An
# autoincrementing column helps around this, but Django doesn't support it natively. As
# a bonus SQLite already has a rowid, so we use the same name for Postgres.
def add_rowid(apps, schema_editor):
    if "postgres" in settings.DATABASES["default"]["ENGINE"]:
        with connection.cursor() as cursor:
            for name in ("user", "domain", "resource","userdomainrole", "userresourcerole"):
                cursor.execute("alter table triplea_%s add column rowid bigserial" % name)
                cursor.execute("create index on triplea_%s(rowid)" % name)


class Migration(migrations.Migration):

    dependencies = [
        ('triplea', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_rowid)
    ]
