# Generated by Django 4.0.1 on 2022-08-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triplea', '0002_counters'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='application',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
