# Generated by Django 6.0.5 on 2026-05-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triplea', '0004_rename_application_user_application_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='descendant_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='domain',
            name='resource_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
