"""
Django settings for dominion project.

Generated by 'django-admin startproject' using Django 4.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

from celery.schedules import crontab
from django.core.exceptions import ImproperlyConfigured
from environs import Env


env = Env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", True)

# SECURITY WARNING: keep the secret key used in production secret!
# In development an insecure default is provided so the app runs without config.
# In production (DEBUG=False) SECRET_KEY must be supplied via the environment; we
# fail fast rather than silently ship the well-known insecure key.
_INSECURE_SECRET_KEY = "django-insecure-^r#(8oga*$i%x7#-xd*et27oqihs*a5b84&ms@@aez9xhu7a7%"
if DEBUG:
    SECRET_KEY = env.str("SECRET_KEY", _INSECURE_SECRET_KEY)
else:
    SECRET_KEY = env.str("SECRET_KEY", None)
    if not SECRET_KEY or SECRET_KEY == _INSECURE_SECRET_KEY:
        raise ImproperlyConfigured(
            "SECRET_KEY environment variable must be set to a unique secret value "
            "when DEBUG is False."
        )

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", ["*"])

# CORS origins for the Connexion API (consumed in main.py). Defaults to a wildcard
# in development; set CORS_ALLOWED_ORIGINS (comma-separated) in production. A wildcard
# origin cannot be combined with credentialed requests, so credentials are only
# enabled when an explicit origin list is configured.
CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS", ["*"])
CORS_ALLOW_CREDENTIALS = env.bool("CORS_ALLOW_CREDENTIALS", False)


# Application definition

INSTALLED_APPS = [
    "dominion",
    "dominion.mail",
    "dominion.registration",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'oauth2_provider',
    "mozilla_django_oidc",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "dominion.middleware.oauth_complete_process",
]

ROOT_URLCONF = "dominion.conf.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "dominion.conf.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    "default": {
        **env.dj_db_url(
            "DATABASE_URL",
            "sqlite:///" + str(BASE_DIR / "db.sqlite3")
        ),
    },
}

# Tune postgres
if "postgres" in DATABASES["default"]["ENGINE"]:
    DATABASES["default"]["CONN_MAX_AGE"] = 60
    DATABASES["default"]["CONN_HEALTH_CHECKS"] = True
    DATABASES["default"]["OPTIONS"] = {"options": "-c statement_timeout=10000"}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom settings added from here
AUTH_USER_MODEL = "dominion.User"

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = "/"

OAUTH2_PROVIDER = {
    "OIDC_ENABLED": True,
    "SCOPES": {
        "openid": "Authenticate you via your account",
        "profile": "Read your first name and last name",
        "email": "Read your email address",
        "read": "Read items related to only the application",
        "write": "Write items related to only the application",
    },
    "OAUTH2_VALIDATOR_CLASS": "dominion.oauth_validators.CustomOAuth2Validator",
}

SESSION_COOKIE_NAME = "dominionid"

# We need a distributed cache for production
if not DEBUG:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.memcached.PyMemcacheCache",
            "LOCATION": env.str("MEMCACHED_LOCATION", "localhost:11211"),
            "KEY_PREFIX": env.str("MEMCACHED_KEY_PREFIX", "inventory"),
        }
    }

    # Session. Cached database is best.
    SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"

RATELIMIT_USE_CACHE = "default"

MEDIA_ROOT = env.str("MEDIA_ROOT", "")
STATIC_ROOT = env.str("STATIC_ROOT", "")

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 100
}


DOMINION_API_RESULTS_PER_PAGE = 100
DOMINION_MAX_DESCENDANT_DOMAINS = 1000
DOMINION_MAX_RESOURCES_PER_DOMAIN = 10000000

CELERY_BEAT_SCHEDULE = {
    'every-5-minutes': {
        'task': 'dominion.mail.tasks.send_unsent_mails',
        'schedule': 300.0,
        'options': {
            'expires': 60.0,
        },
    },
    'daily': {
        'task': 'dominion.mail.tasks.vacuum',
        'schedule': crontab(minute=15, hour=1),
        'options': {
            'expires': 60.0,
        },
    },
}

# Django registration window
ACCOUNT_ACTIVATION_DAYS = 7
REGISTRATION_SALT = "dominion-salt-here"

# Mail settings. See Django docs and mail.backends for options.
EMAIL_BACKEND = env.str("EMAIL_BACKEND", 'dominion.mail.backends.CeleryFileBackend')
EMAIL_FILE_PATH = '/tmp/app-messages'
AWS_ACCESS_KEY_ID = env.str("AWS_ACCESS_KEY_ID", 'YOUR-ACCESS-KEY-ID')
AWS_SECRET_ACCESS_KEY = env.str("AWS_SECRET_ACCESS_KEY", 'YOUR-SECRET-ACCESS-KEY')

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "dominion.audit": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}
