# Generated by Django 4.0.1 on 2022-08-28 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dominion', '0003_user_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='application',
            new_name='application_id',
        ),
    ]
