# Generated by Django 6.0.5 on 2026-07-17 02:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominion', '0006_populate_domain_counters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
