# Generated by Django 6.0.5 on 2026-07-18 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dominion", "0007_alter_user_api_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="domain",
            name="descendant_count",
        ),
        migrations.RemoveField(
            model_name="domain",
            name="resource_count",
        ),
    ]
