# Generated by Django 4.0.1 on 2022-04-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominion_mail', '0002_alter_emailmessage_pickled'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='sent',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
