# Generated by Django 4.0.1 on 2022-04-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominion_mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='pickled',
            field=models.BinaryField(),
        ),
    ]
