# Generated by Django 6.0.5 on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):
    """Step 1 of 3: add the structured email fields alongside the old pickled column.

    Step 2 (0005) is a data migration that populates these fields from pickle.
    Step 3 (0006) removes the old pickled column.
    """

    dependencies = [
        ('triplea_mail', '0003_emailmessage_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='bcc',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='cc',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='from_email',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='headers',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='reply_to',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='subject',
            field=models.CharField(default='', max_length=998),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='to',
            field=models.JSONField(default=list),
        ),
    ]
