# Generated by Django 6.0.5 on 2026-05-07

from django.db import migrations


class Migration(migrations.Migration):
    """Step 3 of 3: remove the old pickled column now that the data has been migrated."""

    dependencies = [
        ("triplea_mail", "0005_populate_emailmessage_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailmessage",
            name="pickled",
        ),
    ]
